module.exports = {
  // * success messages
  SUCCESS_MSG: "Successfully Data Fetch",
  IMG_REQUIRED: "Image is Required",
  SUCCESS_INSERT: "Record Sucessfully Inserted.",
  SUCCESS_UPDATE: "Record Sucessfully Updated.",
  SUCCESS_FOLLOW: "Follow Sucessfully.",
  SUCCESS_UNFOLLOW: "Unfollow Sucessfully.",
  SUCCESS_LIKE: "Like Sucessfully.",
  SUCCESS_UNLIKE: "Unlike Sucessfully.",
  SUCCESS_DELETE: "Record Sucessfully Deleted.",
  SUCCESS_ACTIVE: "Record Sucessfully Activated.",
  SUCCESS_DEACTIVE: "Record Sucessfully Deactivated.",
  SUCCESS_LOGIN: "Successfully logged in.",
  SUCCESS_RESETPASS: "Password Successfully Updated",
  SUCCESS_PAYMENT: "Payment done Successfully",
  SUCCESS_FETCH: "Successfully Fetch",
  // * fail messages
  FAIL_TO_SAVE: "Fail to save the data",
  FAIL_TO_DELETE: "Fail to delete the data",
  FAIL_USER: "Please check username or password",
  NO_TOKEN: "No token, authorization denied",
  NO_AUTHORIZE: "No authorize user for this action",
  NOT_VALID_TOKEN: "Token is not valid",
  NO_USER_FOUND: "No such user",
  FAIL_LIVE: "Fail to get live Data",
  RECORD_EMPTY: "Record list is empty",
  INVALID_DATA: "Invalid data",
  // * exists messages
  RECORD_EXISTS: "record already exists",
  NOT_FOUND: "Record Not Found",
  USER_EMAIL_EXISTS: "Email has been already registered.",
  USER_EMAIL_NOT_EXISTS: "Email Does Not Exists",
  // * other messages
  PASSWORD_UPDATE: "Password Successfully Updated",
  UNAUTHORIZED_USER: "You Are Not Authorize To Do",
  BLOKED_USER: "Login is not allowed.You are bloked",
  EXPIRED_TIME_PERIOD: "Login Time Period Completed. Request Admin To Login.",
  FILTER_MESSAGE: "Select item for filter product",
  MAIL_SEND: "Email Sucessfully Send",
  NOT_MATCH_OLDPASSWORD: "OLD Password Not Match",
  LIMIT_OVER: "Upload Limit Exceeded.",
  TOKEN_EXPIRED: "Token Expired, Please generate new token by sending password reset request again.",
};
